image: docker:latest
services:
  - name: docker:18.09.7-dind
    command: ["--insecure-registry=harbor.toolchain"]

variables:
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/5408
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  BUILD_VERSION: 1.0.0-SNAPSHOT
  VARIABLES_FILE: ./variables.txt
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build


maven-test:
  image: maven:3-jdk-8
  stage: test
  script:
    - "echo 'test valid'"
  allow_failure: true
  only:
    - master

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - "mvn clean package -DskipTests"
  only:
    - master
  artifacts:
    paths:
      - target/*.jar
