image: docker:latest
services:
  - name: docker:18.09.7-dind
    command: ["--insecure-registry=harbor.toolchain"]

variables:
  # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/5408
  DOCKER_HOST: tcp://localhost:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  BUILD_VERSION: 1.0.0-SNAPSHOT
  VARIABLES_FILE: ./variables.txt
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

cache:
  paths:
    - .m2/repository

stages:
  - test
  - build
  - package
  - deploy


maven-test:
  image: maven:3-jdk-8
  stage: test
  variables:
    SONAR_TOKEN: "7d5e155f536a82e424079f8105806f5fa24718ba"
    SONAR_HOST_URL: "https://sonarqube.telekinesis.shop"
  script:
    - "mvn clean verify sonar:sonar -Dsonar.qualitygate.wait=true"
  allow_failure: true
  only:
    - master

maven-build:
  image: maven:3-jdk-8
  stage: build
  script:
    - "mvn clean deploy -s .mvn/ci_settings.xml -DskipTests"
  only:
    - master
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - TAG_VERSION="1.0.$(date '+%Y%m%d')-$CI_COMMIT_SHORT_SHA"
    - echo "export TAG_VERSION=$TAG_VERSION" > $VARIABLES_FILE
    - docker build -t $HARBOR_DOMAIN/sample-spring/demo:$TAG_VERSION --build-arg BUILD_VERSION=$BUILD_VERSION -f Dockerfile .
    - echo "$HARBOR_PASSWORD" | docker login $HARBOR_DOMAIN -u $HARBOR_USERNAME --password-stdin
    - docker push $HARBOR_DOMAIN/sample-spring/demo:$TAG_VERSION
  only:
    - master
  artifacts:
    paths:
      - $VARIABLES_FILE

k8s-deploy:
  image: curlimages/curl
  stage: deploy
  script:
    - source $VARIABLES_FILE
    - |
      curl -vX POST https://$SPINNAKER_DOMAIN/api/webhooks/webhook/sample-spring \
      --data "{\"status\": \"success\", \"secretKey\": \"$SPINNAKER_WEBHOOK_SECRET_KEY\", \"message\": \"I've got it\", \"parameters\": {\"imageTag\":\"$TAG_VERSION\"}}" \
      --header "Content-Type: application/json"
  only:
    - master
