apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '3'
    traffic.spinnaker.io/load-balancers: '["service sample-spring-svc"]'
  labels:
    app: sample-spring-app
  name: sample-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sample-spring-app
  template:
    metadata:
      labels:
        app: sample-spring-app
    spec:
      containers:
        - image: 'harbor.toolchain/sample-spring/demo:${parameters.imageTag}'
          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: sample-spring-app
          ports:
            - containerPort: 8080
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
      imagePullSecrets:
        - name: harbor

